INSERT INTO gun_attachments (name, type, gun_id) VALUES
('Granulated Grip Tape', 'Grip', 1),
('Stippled Grip Tape', 'Grip', 1),
('FSS Raider Stock', 'Grip', 1),
('Lightweight Supressor', 'Muzzle', 1),
('Monolotic Supressor', 'Muzzle', 1),
('Tactical Supressor', 'Muzzle', 1),
('Forge Tac Stalker', 'Stock', 1),
('FTAC hunter', 'Stock', 1),
('FTAC', 'Stock', 1),
('Operator Reflex Sight', 'Optic', 1),
('Aim-Op Reflex Sight', 'Optic', 1),
('Viper Reflex Sight', 'Optic', 1),
('Monocle Reflex Sight', 'Optic', 1),
('Integral Hybrid', 'Optic', 1),
('VLK Optic', 'Optic', 1),
('1mW Laser', 'Laser', 1),
('5mW Laser', 'Laser', 1),
('Tac Laser', 'Laser', 1),
('Fast-Melee', 'Perk', 1),
('Recon', 'Perk', 1),
('FMJ', 'Perk', 1),
('Sleight of Hand', 'Perk', 1),
('Heavy Hitter', 'Perk', 1),
('Fragible - Wounding', 'Perk', 1),
('Fully Loaded', 'Perk', 1),
('Focus', 'Perk', 1),
('Akimbo', 'Perk', 1),
('Lowest Mag', 'Magazine', 1),
('Medium Mag', 'Magazine', 1),
('Highest Mag', 'Magazine', 1),
('First Available Barrel', 'Barrel', 1),
('Second Available Barrel', 'Barrel', 1),
('Last Available Barrel', 'Barrel', 1),
('Fully Loaded', 'Barrel', 1),
('Focus', 'Barrel', 1),
('Akimbo', 'Barrel', 1);
