INSERT INTO gun_attachments (name, image, type, gun_id) 
values 
('Granulated Grip Tape', '../img/trainstation-weapon.jpeg', 'Grip', 1),
('Stippled Grip Tape', '../img/trainstation-weapon.jpeg', 'Grip', 1),
('FSS Raider Stock', '../img/trainstation-weapon.jpeg', 'Grip', 1),
('Lightweight Supressor', '../img/trainstation-weapon.jpeg', 'Muzzle', 1),
('Monolotic Supressor', '../img/trainstation-weapon.jpeg', 'Muzzle', 1),
('Tactical Supressor', '../img/trainstation-weapon.jpeg', 'Muzzle', 1),
('Forge Tac Stalker', '../img/trainstation-weapon.jpeg', 'Stock', 1),
('FTAC hunter', '../img/trainstation-weapon.jpeg', 'Stock', 1),
('FTAC', '../img/trainstation-weapon.jpeg', 'Stock', 1),
('Operator Reflex Sight', '../img/trainstation-weapon.jpeg', 'Optic', 1),
('Aim-Op Reflex Sight', '../img/trainstation-weapon.jpeg', 'Optic', 1),
('Viper Reflex Sight', '../img/trainstation-weapon.jpeg', 'Optic', 1),
('Monocle Reflex Sight', '../img/trainstation-weapon.jpeg', 'Optic', 1),
('Integral Hybrid', '../img/trainstation-weapon.jpeg', 'Optic', 1),
('VLK Optic', '../img/trainstation-weapon.jpeg', 'Optic', 1),
('1mW Laser', '../img/trainstation-weapon.jpeg', 'Laser', 1),
('5mW Laser', '../img/trainstation-weapon.jpeg', 'Laser', 1),
('Tac Laser', '../img/trainstation-weapon.jpeg', 'Laser', 1),
('Fast-Melee', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Recon', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('FMJ', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Sleight of Hand', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Heavy Hitter', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Fragible - Wounding', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Fully Loaded', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Focus', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Akimbo', '../img/trainstation-weapon.jpeg', 'Perk', 1),
('Lowest Mag', '../img/trainstation-weapon.jpeg', 'Magazine', 1),
('Medium Mag', '../img/trainstation-weapon.jpeg', 'Magazine', 1),
('Highest Mag', '../img/trainstation-weapon.jpeg', 'Magazine', 1),
('First Available Barrel', '../img/trainstation-weapon.jpeg', 'Barrel', 1),
('Second Available Barrel', '../img/trainstation-weapon.jpeg', 'Barrel', 1),
('Last Available Barrel', '../img/trainstation-weapon.jpeg', 'Barrel', 1),
('Fully Loaded', '../img/trainstation-weapon.jpeg', 'Barrel', 1),
('Focus', '../img/trainstation-weapon.jpeg', 'Barrel', 1),
('Akimbo', '../img/trainstation-weapon.jpeg', 'Barrel', 1);
