INSERT INTO guns (name, category) VALUES
('MP5', 'SMG'),
('MP7', 'SMG'),
('AUG', 'SMG'),
('Mac-10', 'SMG'),
('P90', 'SMG'),
('PP19 Bizon', 'SMG'),
('Uzi', 'SMG'),
('Striker 45', 'SMG'),
('Fennec', 'SMG'),
('ISO SMG', 'SMG'),
('AK47', 'AR'),
('M13', 'AR'),
('FR 5.56', 'AR'),
('FN SCAR 17', 'AR'),
('FAL', 'AR'),
('RAM-7', 'AR'),
('CR-56 AMAX', 'AR'),
('Killo141', 'AR'),
('Oden', 'AR'),
('AS VAL', 'AR'),
('Rytec AMR (Barret)', 'Sniper'),
('AX-50', 'Sniper'),
('Draganov', 'Sniper'),
('HDR', 'Sniper'),
('EBR-14', 'Sniper'),
('KAR98K', 'Sniper'),
('MK2 Carbine', 'Sniper'),
('Crossbow', 'Sniper'),
('SKS', 'Sniper'),
('SP-R 208', 'Sniper'),
('X16', 'Pistol'),
('1911', 'Pistol'),
('.357', 'Pistol'),
('.50 GS', 'Pistol'),
('M19', 'Pistol'),
('Renetti', 'Pistol'),
('Butterfly Knife', 'Melees'),
('Try Fist', 'Melees'),
('knife', 'Melees'),
('Axe', 'Melees'),
('Riot Shield', 'Melees'),
('Model 680', 'Shotgun'),
('R9-0 Shotgun', 'Shotgun'),
('725', 'Shotgun'),
('Origin 12 Shotgun', 'Shotgun'),
('VLK Rouge', 'Shotgun'),
('JAK-12', 'Shotgun'),
('M91', 'Light Machine Gun'),
('PKM', 'Light Machine Gun'),
('MG34', 'Light Machine Gun'),
('SA87', 'Light Machine Gun'),
('MK9 Bruen', 'Light Machine Gun'),
('FiNN', 'Light Machine Gun'),
('holger-26', 'Light Machine Gun'),
('RPG-7', 'Launchers'),
('PILA', 'Launchers'),
('JOKR', 'Launchers'),
('Strela-P', 'Launchers');



