INSERT INTO tactical_lethal (name, type) VALUES
('Claymore', 'Lethal'),
('Frag', 'Lethal'),
('Molotove Cocktail', 'Lethal'),
('C4', 'Lethal'),
('Semtex', 'Lethal'),
('Throwing Knife', 'Lethal'),
('Proximity Mine', 'Lethal'),
('Thermite', 'Lethal'),
('Flaming Throwing Knife', 'Lethal'),
('Flash Grenade', 'Tactical'),
('Stun Grenade', 'Tactical'),
('Smoke Grenade', 'Tactical'),
('Snapshot Grenade', 'Tactical'),
('Heartbeat', 'Tactical'),
('Gas Grenade', 'Tactical'),
('Stim', 'Tactical'),
('Decoy Grenade', 'Tactical');